version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        RUBY_VERSION: 3.4.3
        NODE_VERSION: 22
    environment:
      RAILS_ENV: production
      BUNDLE_DEPLOYMENT: 1
      BUNDLE_WITHOUT: "development:test"
      BUNDLE_PATH: "/usr/local/bundle"
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@db:5432/reordersweb_production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./storage:/rails/storage
      - ./log:/rails/log
    restart: unless-stopped

  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: reordersweb_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local