version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        RUBY_VERSION: 3.4.3
        NODE_VERSION: 22
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - reorders_storage:/rails/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  reorders_storage: