service: reordersweb

image: ghcr.io/shirtpop/reordersweb:latest

registry:
  server: ghcr.io
  username: KAMAL_REGISTRY_USERNAME

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: 1
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

ssh:
  user: deploy
  keepalive: true
  keys:
    - ~/.ssh/shirtpop

volumes:
  - "reordersweb_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  multiarch: true

