default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  

development:
  <<: *default
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

test:
  <<: *default

staging:
  dispatchers:
    - polling_interval: 5
      batch_size: 50
  workers:
    - queues: "*"
      threads: 2
      processes: 1
      polling_interval: 5

production:
  <<: *default
  workers:
    - queues: "*"
      threads: 3
      processes: 3
      polling_interval: 1
